package(default_visibility = ["//visibility:public"])

test_suite(
    name = "miri",
    testonly = True,
    tags = [
        "manual",
        "miri",
    ],
    tests = [
        "//base:base_miri",
        "//exact_replay_executor:exact_replay_executor_miri",
        "//examples/facet_serialization:facet_serialization_miri",
        "//live_executor:live_executor_miri",
        "//live_replay_executor:live_replay_executor_miri",
        "//logging:logging_miri",
        "//logging_test:event_logging_test_miri",
        "//logging_test:logging_build_step_test_miri",
        "//simulation_executor:simulation_executor_miri",
        "//task:task_miri",
        "//task_macros:task_macros_test_miri",
        "//testing:testing_miri",
    ],
)
