[package]
name = "live_executor"
version = "0.1.0"
edition = "2024"

[lib]

[features]
default = ["iceoryx2"]
iceoryx2 = ["task/iceoryx2", "dep:iceoryx2"]

[dependencies]
task = { path = "../task", default-features = false }
crossbeam = "0.8"
iceoryx2 = { workspace = true, optional = true }

[dev-dependencies]
test_tasks = { path = "../test_tasks" }
task = { path = "../task", features = ["testing"] }
assert_no_alloc = {
    # Only the git release has backtrace support
    git = "https://github.com/Windfisch/rust-assert-no-alloc", rev="95120d996240a2c279a6067502e11b62d30563a6",
    # Disable default features so that we panic on allocations
    default-features = false,
    features=["backtrace"]
}

[lints]
workspace = true
