[package]
name = "logging"
version = "0.1.0"
edition = "2024"

[dependencies]
task = { path = "../task" }
task_macros = { path = "../task_macros" }
serde = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json", "task/serde"]

[dev-dependencies]
task = { path = "../task", features = ["testing"] }
testing = { path = "../testing" }
simulation_executor = { path = "../simulation_executor" }

[lints]
workspace = true
