load("//bazel:rust.bzl", "miri_test", "rust_library", "rust_test")
load("@crates//:defs.bzl", "all_crate_deps")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "exact_replay_executor",
    srcs = glob(["src/**/*.rs"]),
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "exact_replay_executor_unit_tests",
    crate = ":exact_replay_executor",
    deps = all_crate_deps(normal_dev = True),
)

rust_test(
    name = "forwarded_replay_test",
    srcs = ["tests/forwarded_replay.rs"],
    deps = [":exact_replay_executor"] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "reproduce_unlogged_test",
    srcs = ["tests/reproduce_unlogged.rs"],
    deps = [":exact_replay_executor"] + all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

miri_test(
    name = "exact_replay_executor_miri",
    srcs = glob(["src/**/*.rs"]),
    deps = all_crate_deps(normal = True),
)
