[package]
name = "exact_replay_executor"
version = "0.1.0"
edition = "2024"

[features]
default = ["iceoryx2"]
iceoryx2 = ["task/iceoryx2", "logging/iceoryx2", "dep:iceoryx2"]

[dependencies]
base = { path = "../base" }
task = { path = "../task", default-features = false, features = ["serde"] }
logging = { path = "../logging", default-features = false, features = ["serde"] }
iceoryx2 = { workspace = true, optional = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
task_macros = { path = "../task_macros" }

[lints]
workspace = true
