load("//bazel:rust.bzl", "miri_test", "rust_test")
load("@crates//:defs.bzl", "all_crate_deps")

package(default_visibility = ["//visibility:public"])

rust_test(
    name = "recording_test",
    srcs = ["tests/recording.rs"],
    deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

miri_test(
    name = "recording_test_miri",
    srcs = ["tests/recording.rs"],
    deps = all_crate_deps(normal = True),
)
