load("//bazel:rust.bzl", "miri_test", "rust_test")
load("@crates//:defs.bzl", "all_crate_deps")

package(default_visibility = ["//visibility:public"])

rust_test(
    name = "event_logging_test",
    srcs = ["tests/event_logging_test.rs"],
    deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

rust_test(
    name = "logging_build_step_test",
    srcs = ["tests/logging_build_step_test.rs"],
    deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)

miri_test(
    name = "event_logging_test_miri",
    srcs = ["tests/event_logging_test.rs"],
    deps = all_crate_deps(normal = True),
)

miri_test(
    name = "logging_build_step_test_miri",
    srcs = ["tests/logging_build_step_test.rs"],
    deps = all_crate_deps(normal = True),
)
