use crate::executor::CallbackNodeEnqueuer;
use crate::generic_publisher::GenericPublisher;
use crate::generic_subscriber::GenericSubscriber;
use crate::message::MessageHeader;
use crate::pub_sub::{CallbackNodeName, ChannelName};
use crate::publisher::PublisherConfig;
use crate::subscriber::SubscriberConfig;
use crate::time::FrameworkTime;
use std::collections::HashMap;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, OnceLock};
use std::time::Duration;

#[derive(Debug, Clone, PartialEq)]
pub enum InputKind {
    Required,
    Optional,
    Span,
}

impl From<InputKind> for SubscriberConfig {
    fn from(val: InputKind) -> Self {
        match val {
            InputKind::Required => SubscriberConfig {
                is_optional: false,
                capacity: 1,
                is_trigger: true,
                keep_across_runs: true,
                // TODO, dont default this
                channel_name: "".into(),
            },
            InputKind::Optional => SubscriberConfig {
                is_optional: true,
                capacity: 1,
                is_trigger: true,
                keep_across_runs: true,
                // TODO, dont default this
                channel_name: "".into(),
            },
            InputKind::Span => SubscriberConfig {
                is_optional: true,
                // TODO, dont default this
                capacity: 4,
                is_trigger: true,
                keep_across_runs: true,
                // TODO, dont default this
                channel_name: "".into(),
            },
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum OutputKind {
    Default,
    Span,
}
impl From<OutputKind> for PublisherConfig {
    fn from(_val: OutputKind) -> Self {
        PublisherConfig {
            capacity: 1,
            // TODO, dont default this
            channel_name: "".into(),
        }
    }
}

#[derive(Debug)]
pub struct Run {
    pub num_iterations: usize,
}

impl Run {
    pub fn new(num_iterations: usize) -> Run {
        Run { num_iterations }
    }
}

// ── PortMut ──

/// One mutable port visit — lets callers collect *both* subscriber and
/// publisher mut-views from a single `&mut self` borrow.
pub enum PortMut<'a> {
    Subscriber(&'a mut dyn GenericSubscriber),
    Publisher(&'a mut dyn GenericPublisher),
}

// ── New Callback trait ──

pub trait Callback {
    fn run(&mut self, ctx: &crate::context::Context) -> Run;

    fn for_each_subscriber<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericSubscriber));
    fn for_each_publisher<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericPublisher));
    fn for_each_subscriber_mut<'a>(&'a mut self, f: &mut dyn FnMut(&'a mut dyn GenericSubscriber));
    fn for_each_publisher_mut<'a>(&'a mut self, f: &mut dyn FnMut(&'a mut dyn GenericPublisher));
    fn for_each_port_mut<'a>(&'a mut self, f: &mut dyn FnMut(PortMut<'a>));

    fn drain_subscribers(&self) {
        self.for_each_subscriber(&mut |s| s.drain_writer_to_reader());
    }

    fn flush_publishers(&mut self, timestamp: FrameworkTime) {
        self.for_each_publisher_mut(&mut |p| p.flush_loaned_values(timestamp));
    }

    fn flush_publishers_logged(
        &mut self,
        timestamp: FrameworkTime,
        hook: &mut dyn FnMut(usize, &MessageHeader),
    ) {
        let mut ordinal = 0;
        self.for_each_publisher_mut(&mut |p| {
            p.flush_loaned_values_logged(timestamp, &mut |h| hook(ordinal, h));
            ordinal += 1;
        });
    }

    fn subscribers_request_execution(&self) -> bool {
        let mut any = false;
        self.for_each_subscriber(&mut |s| any |= s.requests_execution());
        any
    }

    fn able_to_run(&self) -> bool {
        let mut all = true;
        self.for_each_subscriber(&mut |s| all &= s.able_to_run());
        all
    }

    fn required_inputs_ready(&self) -> bool {
        let mut ready = true;
        self.for_each_subscriber(&mut |s| {
            ready &= s.config().is_optional || s.has_data_available();
        });
        ready
    }

    /// Register this callback's channels (and value types, if loggable) into
    /// `registry`. Called by `TaskGraphBuilder::build()` for every node in the
    /// graph. Generated by `#[task_callback]`, which knows each port's payload
    /// type statically and uses [`Probe`](crate::channel_registry::Probe) to
    /// register loggable channels. Hand-written callbacks can implement this
    /// manually; the default is a no-op.
    fn register_channels(&self, _registry: &mut crate::channel_registry::ChannelRegistry) {}
}

// ── CallbackViews extension (setup-time Vec helpers) ──

pub trait CallbackViews: Callback {
    fn collect_subscribers(&self) -> Vec<&dyn GenericSubscriber> {
        let mut v = Vec::new();
        self.for_each_subscriber(&mut |s| v.push(s));
        v
    }
    fn collect_publishers(&self) -> Vec<&dyn GenericPublisher> {
        let mut v = Vec::new();
        self.for_each_publisher(&mut |s| v.push(s));
        v
    }
    fn collect_subscribers_mut(&mut self) -> Vec<&mut dyn GenericSubscriber> {
        let mut v = Vec::new();
        self.for_each_subscriber_mut(&mut |s| v.push(s));
        v
    }
    fn collect_publishers_mut(&mut self) -> Vec<&mut dyn GenericPublisher> {
        let mut v = Vec::new();
        self.for_each_publisher_mut(&mut |s| v.push(s));
        v
    }
    fn collect_ports_mut(
        &mut self,
    ) -> (
        Vec<&mut dyn GenericSubscriber>,
        Vec<&mut dyn GenericPublisher>,
    ) {
        let mut subs = Vec::new();
        let mut pubs = Vec::new();
        self.for_each_port_mut(&mut |port| match port {
            PortMut::Subscriber(s) => subs.push(s),
            PortMut::Publisher(p) => pubs.push(p),
        });
        (subs, pubs)
    }
}

impl<T: Callback + ?Sized> CallbackViews for T {}

// ── MismatchTypeError ──

#[derive(Debug)]
pub struct MismatchTypeError {
    channel_name: ChannelName,
    publisher_callback_node: CallbackNodeName,
    subscriber_callback_node: CallbackNodeName,
}

impl std::fmt::Display for MismatchTypeError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "Callback node '{}' publishes on '{}' but subscriber callback node '{}' has a different type for that channel",
            self.publisher_callback_node, self.channel_name, self.subscriber_callback_node
        )
    }
}

impl std::error::Error for MismatchTypeError {}

// ── Forwarded channel usage ──

/// Returns a mapping of the forwarded channel to the depth of subscriber queues listening to it
fn find_forwarded_channel_usage(callbacks: &[CallbackNode]) -> HashMap<ChannelName, usize> {
    let mut usage = HashMap::<ChannelName, usize>::new();

    for node in callbacks {
        node.callback().for_each_publisher(&mut |p| {
            for fc in p.forwarded_channels() {
                usage.entry(fc.clone()).or_insert(0);
            }
        });
    }

    for node in callbacks {
        node.callback().for_each_subscriber(&mut |s| {
            let ch = &s.config().channel_name;
            if let Some(u) = usage.get_mut(ch) {
                *u += s.config().arena_footprint();
            }
        });
    }

    usage
}

// ── connect_callback_nodes ──

/// Connects publishers to subscribers and sizes arenas accordingly
pub fn connect_callback_nodes(callbacks: &mut [CallbackNode]) -> Result<(), MismatchTypeError> {
    let n = callbacks.len();
    let names: Vec<String> = callbacks.iter().map(|n| n.name().to_string()).collect();
    let forwarded_usage = find_forwarded_channel_usage(callbacks);

    let mut all_subs: Vec<Vec<&mut dyn GenericSubscriber>> = Vec::with_capacity(n);
    let mut all_pubs: Vec<Vec<&mut dyn GenericPublisher>> = Vec::with_capacity(n);
    for node in callbacks.iter_mut() {
        let (subs, pubs) = node.callback_mut().collect_ports_mut();
        all_subs.push(subs);
        all_pubs.push(pubs);
    }

    for i in 0..n {
        for j in 0..n {
            for publisher in all_pubs[i].iter_mut() {
                for subscriber in all_subs[j].iter_mut() {
                    if publisher.config().channel_name == subscriber.config().channel_name {
                        println!(
                            "Connecting callback node '{}' to callback node '{}' on channel '{}'",
                            names[i],
                            names[j],
                            publisher.config().channel_name
                        );
                        if publisher.connect_to_subscriber(&mut **subscriber).is_err() {
                            return Err(MismatchTypeError {
                                channel_name: publisher.config().channel_name.clone(),
                                publisher_callback_node: names[i].clone(),
                                subscriber_callback_node: names[j].clone(),
                            });
                        }
                    }
                }
                if let Some(usage) = forwarded_usage.get(&publisher.config().channel_name) {
                    publisher.increase_arena_size(*usage);
                }
            }
        }
    }

    for pubs in all_pubs.iter_mut() {
        for publisher in pubs.iter_mut() {
            publisher.allocate_arena();
        }
    }

    Ok(())
}

// ── Readiness (unchanged) ──

/// Tracks readiness of the gating (required / non-optional) subscribers in a
/// CallbackNode via an atomic bitmask. Each gating subscriber's bit is 0 (not
/// ready) or 1 (ready); optional subscribers and unused high bits are always 1.
/// When the bitmask reaches usize::MAX, every required input has data and the
/// callback node can be enqueued. A trigger input's bit means "new event
/// pending" and is cleared when the node drains it; a non-trigger input's bit
/// means "has a value" and stays set while its read buffer retains one.
pub struct CallbackNodeReadiness {
    bitmask: AtomicUsize,
    node_index: OnceLock<usize>,
    enqueuer: OnceLock<Arc<dyn CallbackNodeEnqueuer>>,
}

impl CallbackNodeReadiness {
    fn new(initial_bitmask: usize) -> Arc<Self> {
        Arc::new(CallbackNodeReadiness {
            bitmask: AtomicUsize::new(initial_bitmask),
            node_index: OnceLock::new(),
            enqueuer: OnceLock::new(),
        })
    }

    /// Set bit `index`, then enqueue the callback node if this was the transition to usize::MAX.
    /// Only enqueues when the bitmask was not already MAX before this call.
    pub fn set_bit(&self, index: usize) {
        let bit = 1usize << index;
        let prev = self.bitmask.fetch_or(bit, Ordering::AcqRel);
        if prev != usize::MAX
            && prev | bit == usize::MAX
            && let (Some(enqueuer), Some(&node_index)) =
                (self.enqueuer.get(), self.node_index.get())
        {
            enqueuer.enqueue_node(node_index);
        }
    }

    /// Clear bit `index` (called when the callback node drains write→read for this subscriber).
    pub fn clear_bit(&self, index: usize) {
        let mask = !(1usize << index);
        self.bitmask.fetch_and(mask, Ordering::AcqRel);
    }

    /// Register the executor enqueuer and node index. If the bitmask is already MAX
    /// (e.g., startup with pre-loaded data), immediately enqueue.
    pub fn register(&self, node_index: usize, enqueuer: Arc<dyn CallbackNodeEnqueuer>) {
        let _ = self.node_index.set(node_index);
        let _ = self.enqueuer.set(enqueuer);
        self.enqueue_if_ready();
    }

    /// Enqueue the node if every required input currently has a value
    /// (bitmask == usize::MAX). Called when an optional+trigger subscriber
    /// receives data: the data is a trigger, but the node may only run once
    /// its required inputs are ready. The executor dedups duplicate enqueues.
    pub fn enqueue_if_ready(&self) {
        if self.bitmask.load(Ordering::Acquire) == usize::MAX
            && let (Some(enqueuer), Some(&idx)) = (self.enqueuer.get(), self.node_index.get())
        {
            enqueuer.enqueue_node(idx);
        }
    }
}

/// How a subscriber participates in its node's readiness tracking.
#[derive(Clone)]
pub enum SubscriberReadiness {
    /// Gating (required / non-optional) input: owns the bit at the given
    /// index. Data arrival sets the bit; the node enqueues when all gating
    /// bits are set.
    Gating(Arc<CallbackNodeReadiness>, usize),
    /// Optional trigger input: owns no bit (it never gates). Data arrival
    /// enqueues the node if all required inputs are ready.
    OptionalTrigger(Arc<CallbackNodeReadiness>),
}

/// Whether a subscriber gates its node's data-triggered execution: every
/// required (non-optional) input must have data before the node is enqueued.
/// Trigger and non-trigger required inputs differ only in what their bit
/// *means* — a trigger bit is an event consumed by the next run, a
/// non-trigger bit is a retained "has a value" gate — see
/// `Subscriber::drain_writer_to_reader`. These are exactly the subscribers
/// publishers track readiness for — see `Publisher::add_typed_subscriber`.
fn is_gating(subscriber: &dyn GenericSubscriber) -> bool {
    !subscriber.config().is_optional
}

/// Compute the initial bitmask for a set of subscribers.
/// Only gating (required / non-optional) subscribers consume bits, packed
/// densely from bit 0; their bits start at 0 (must receive data). All other
/// bits start at 1.
fn compute_bitmask(gating_count: usize) -> usize {
    const MAX_GATING_SUBSCRIBER_COUNT: usize = std::mem::size_of::<usize>() * 8;
    if gating_count > MAX_GATING_SUBSCRIBER_COUNT {
        panic!(
            "We cannot support callbacks with more than {} required (non-optional) subscribers, try splitting out your callback into multiple callbacks.",
            MAX_GATING_SUBSCRIBER_COUNT
        )
    }
    let mut bitmask = usize::MAX;
    for bit_index in 0..gating_count {
        bitmask &= !(1usize << bit_index);
    }
    bitmask
}

// ── CallbackNode ──

pub struct CallbackNode {
    callback: Box<dyn Callback>,
    next_execution_time_callback: Box<dyn Fn(FrameworkTime) -> Option<FrameworkTime>>,
    execution_duration_callback: Option<Box<dyn Fn() -> Duration>>,
    name: CallbackNodeName,
    readiness: Arc<CallbackNodeReadiness>,
    log_executions: bool,
}

impl std::fmt::Debug for CallbackNode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("CallbackNode")
            .field("name", &self.name)
            .finish_non_exhaustive()
    }
}

impl std::fmt::Display for CallbackNode {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, "Node: {}", self.name)?;
        let mut inputs = Vec::new();
        self.callback.for_each_subscriber(&mut |s| {
            inputs.push(s.config().channel_name.clone());
        });
        let mut outputs = Vec::new();
        self.callback.for_each_publisher(&mut |p| {
            outputs.push(p.config().channel_name.clone());
        });
        writeln!(f, "  inputs:  {:?}", inputs)?;
        write!(f, "  outputs: {:?}", outputs)
    }
}

/// SAFETY: Callbacks may run on any thread, users cannot make thread assumptions
unsafe impl Sync for CallbackNode {}
/// SAFETY: Callbacks may run on any thread, users cannot make thread assumptions
unsafe impl Send for CallbackNode {}

impl CallbackNode {
    pub fn new_named(callback: Box<dyn Callback>, name: CallbackNodeName) -> Self {
        let mut gating_count: usize = 0;
        callback.for_each_subscriber(&mut |s| {
            if is_gating(s) {
                gating_count += 1;
            }
        });
        let readiness = CallbackNodeReadiness::new(compute_bitmask(gating_count));

        let mut node = CallbackNode {
            callback,
            next_execution_time_callback: Box::new(|_| None),
            execution_duration_callback: None,
            name,
            readiness,
            log_executions: false,
        };

        let mut bit_index = 0;
        node.callback.for_each_subscriber_mut(&mut |s| {
            if is_gating(s) {
                s.set_readiness_state(SubscriberReadiness::Gating(
                    node.readiness.clone(),
                    bit_index,
                ));
                bit_index += 1;
            } else if s.config().is_trigger {
                s.set_readiness_state(SubscriberReadiness::OptionalTrigger(node.readiness.clone()));
            }
        });

        node
    }

    pub fn callback(&self) -> &dyn Callback {
        &*self.callback
    }
    pub fn callback_mut(&mut self) -> &mut dyn Callback {
        &mut *self.callback
    }

    pub fn name(&self) -> &str {
        &self.name
    }

    pub fn set_execution_duration_callback(&mut self, cb: Box<dyn Fn() -> Duration>) {
        self.execution_duration_callback = Some(cb);
    }

    pub fn execution_duration(&self) -> Duration {
        (self
            .execution_duration_callback
            .as_ref()
            .expect("execution_duration_callback not set on this CallbackNode"))()
    }

    pub fn set_execution_time_callback(
        &mut self,
        cb: Box<dyn Fn(FrameworkTime) -> Option<FrameworkTime>>,
    ) {
        self.next_execution_time_callback = cb;
    }

    /// The next requested execution time relevant to a current execution time.
    /// 'Instant' is assumed to be provided via a monotonic clock as per rust docs.
    pub fn next_requested_execution_time(&self, now: FrameworkTime) -> Option<FrameworkTime> {
        (self.next_execution_time_callback)(now)
    }

    pub fn drain_subscribers(&mut self) {
        self.callback.drain_subscribers();
    }
    pub fn flush_publishers(&mut self, ts: FrameworkTime) {
        self.callback.flush_publishers(ts);
    }

    pub fn flush_publishers_logged(
        &mut self,
        ts: FrameworkTime,
        hook: &mut dyn FnMut(usize, &MessageHeader),
    ) {
        self.callback.flush_publishers_logged(ts, hook);
    }

    pub fn log_executions(&self) -> bool {
        self.log_executions
    }
    pub fn set_log_executions(&mut self, enabled: bool) {
        self.log_executions = enabled;
    }

    pub fn run(&mut self, ctx: &crate::context::Context) -> Run {
        self.callback.run(ctx)
    }
    pub fn subscribers_request_execution(&self) -> bool {
        self.callback.subscribers_request_execution()
    }
    pub fn required_inputs_ready(&self) -> bool {
        self.callback.required_inputs_ready()
    }
    pub fn able_to_run(&self) -> bool {
        self.callback.able_to_run()
    }

    pub fn register_with_executor(
        &self,
        node_index: usize,
        enqueuer: Arc<dyn CallbackNodeEnqueuer>,
    ) {
        self.readiness.register(node_index, enqueuer);
    }
}

impl Drop for CallbackNode {
    /// Empty subscriber queues before the node is destroyed. In standalone
    /// tests where a publisher's arena outlives this node, leaving ArenaPtrs
    /// in the subscriber buffers would be a use-after-free when the
    /// subscriber's queue drop glue dereferences the stale arena slots.
    /// Executors should still call cleanup on all nodes before tearing down
    /// arenas, but this is a cheap safety net for simple cases.
    fn drop(&mut self) {
        self.callback
            .for_each_subscriber(&mut |s| s.cleanup_buffers());
    }
}

#[cfg(test)]
mod test {
    use super::*;
    use crate::callback::PortMut;
    use crate::subscriber::Subscriber;
    use std::sync::atomic::AtomicUsize;

    fn make_subscriber(is_trigger: bool, is_optional: bool) -> Box<dyn GenericSubscriber> {
        Box::new(Subscriber::<u64>::new(SubscriberConfig {
            is_optional,
            capacity: 1,
            is_trigger,
            keep_across_runs: true,
            channel_name: "".into(),
        }))
    }

    struct VecPorts {
        subs: Vec<Box<dyn GenericSubscriber>>,
        pubs: Vec<Box<dyn GenericPublisher>>,
    }

    impl Callback for VecPorts {
        fn run(&mut self, _ctx: &crate::context::Context) -> Run {
            Run::new(0)
        }
        fn for_each_subscriber<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericSubscriber)) {
            for s in &self.subs {
                f(s.as_ref());
            }
        }
        fn for_each_publisher<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericPublisher)) {
            for p in &self.pubs {
                f(p.as_ref());
            }
        }
        fn for_each_subscriber_mut<'a>(
            &'a mut self,
            f: &mut dyn FnMut(&'a mut dyn GenericSubscriber),
        ) {
            for s in self.subs.iter_mut() {
                f(s.as_mut());
            }
        }
        fn for_each_publisher_mut<'a>(
            &'a mut self,
            f: &mut dyn FnMut(&'a mut dyn GenericPublisher),
        ) {
            for p in self.pubs.iter_mut() {
                f(p.as_mut());
            }
        }
        fn for_each_port_mut<'a>(&'a mut self, f: &mut dyn FnMut(crate::callback::PortMut<'a>)) {
            for s in self.subs.iter_mut() {
                f(crate::callback::PortMut::Subscriber(s.as_mut()));
            }
            for p in self.pubs.iter_mut() {
                f(crate::callback::PortMut::Publisher(p.as_mut()));
            }
        }
    }

    struct NoopCallback;
    impl Callback for NoopCallback {
        fn run(&mut self, _ctx: &crate::context::Context) -> Run {
            Run::new(0)
        }
        fn for_each_subscriber<'a>(&'a self, _f: &mut dyn FnMut(&'a dyn GenericSubscriber)) {}
        fn for_each_publisher<'a>(&'a self, _f: &mut dyn FnMut(&'a dyn GenericPublisher)) {}
        fn for_each_subscriber_mut<'a>(
            &'a mut self,
            _f: &mut dyn FnMut(&'a mut dyn GenericSubscriber),
        ) {
        }
        fn for_each_publisher_mut<'a>(
            &'a mut self,
            _f: &mut dyn FnMut(&'a mut dyn GenericPublisher),
        ) {
        }
        fn for_each_port_mut<'a>(&'a mut self, _f: &mut dyn FnMut(PortMut<'a>)) {}
    }

    struct CountingEnqueuer(Arc<AtomicUsize>);
    impl CallbackNodeEnqueuer for CountingEnqueuer {
        fn enqueue_node(&self, _node_index: usize) {
            self.0.fetch_add(1, Ordering::Relaxed);
        }
    }

    #[test]
    fn test_two_trigger_subscribers_both_must_be_set() {
        let enqueue_count = Arc::new(AtomicUsize::new(0));
        let enqueuer =
            Arc::new(CountingEnqueuer(enqueue_count.clone())) as Arc<dyn CallbackNodeEnqueuer>;
        let initial = compute_bitmask(2);
        let readiness = CallbackNodeReadiness::new(initial);
        readiness.register(0, enqueuer);

        readiness.set_bit(0);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            0,
            "should not enqueue after only one subscriber is ready"
        );
        readiness.set_bit(1);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            1,
            "should enqueue once both subscribers are ready"
        );
        readiness.set_bit(0);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            1,
            "should not enqueue again when bit is already set"
        );
    }

    #[test]
    fn test_loopback_self_subscribe() {
        use crate::context::Context;
        use crate::input::OptionalInput;
        use crate::output::Output;
        use crate::publisher::{Publisher, PublisherConfig};
        use crate::time::FrameworkTime;

        struct LoopbackCallback {
            subscriber: Subscriber<u64>,
            publisher: Publisher<u64>,
            value_to_publish: u64,
            received: Vec<u64>,
        }
        impl Callback for LoopbackCallback {
            fn run(&mut self, _ctx: &Context) -> Run {
                let input = OptionalInput::<u64>::new_downcasted(&mut self.subscriber);
                if let Some(msg) = input.value() {
                    self.received.push(*msg);
                }
                let mut output = Output::<u64>::new_downcasted(&mut self.publisher);
                *output = self.value_to_publish;
                output.send();
                self.value_to_publish += 1;
                Run::new(1)
            }
            fn for_each_subscriber<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericSubscriber)) {
                f(&self.subscriber);
            }
            fn for_each_publisher<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericPublisher)) {
                f(&self.publisher);
            }
            fn for_each_subscriber_mut<'a>(
                &'a mut self,
                f: &mut dyn FnMut(&'a mut dyn GenericSubscriber),
            ) {
                f(&mut self.subscriber);
            }
            fn for_each_publisher_mut<'a>(
                &'a mut self,
                f: &mut dyn FnMut(&'a mut dyn GenericPublisher),
            ) {
                f(&mut self.publisher);
            }
            fn for_each_port_mut<'a>(&'a mut self, f: &mut dyn FnMut(PortMut<'a>)) {
                f(PortMut::Subscriber(&mut self.subscriber));
                f(PortMut::Publisher(&mut self.publisher));
            }
        }

        let callback = LoopbackCallback {
            subscriber: Subscriber::<u64>::new(SubscriberConfig {
                is_optional: true,
                capacity: 1,
                is_trigger: false,
                keep_across_runs: true,
                channel_name: "loopback".into(),
            }),
            publisher: Publisher::<u64>::new(PublisherConfig {
                capacity: 1,
                channel_name: "loopback".into(),
            }),
            value_to_publish: 10,
            received: vec![],
        };

        let mut nodes = vec![CallbackNode::new_named(
            Box::new(callback),
            "LoopbackCallback".into(),
        )];
        connect_callback_nodes(&mut nodes).expect("loopback connection should succeed");

        let ctx = Context {
            now: FrameworkTime::from_nanoseconds(1),
        };
        nodes[0].run(&ctx);
        nodes[0].flush_publishers(ctx.now);
        nodes[0].drain_subscribers();

        nodes[0].run(&ctx);
        nodes[0].flush_publishers(ctx.now);

        let collected = nodes[0].callback().collect_subscribers();
        assert_eq!(
            collected[0].queue_info().writer_size,
            1,
            "loopback: published message should be in subscriber's write buffer"
        );
        nodes[0].drain_subscribers();
        let collected = nodes[0].callback().collect_subscribers();
        assert_eq!(
            collected[0].queue_info().reader_size,
            1,
            "loopback: message should have drained to read buffer"
        );
    }

    #[test]
    fn test_subscriber_bitmask() {
        assert_eq!(compute_bitmask(0), usize::MAX);
        assert_eq!(compute_bitmask(1), usize::MAX - 1);
        assert_eq!(compute_bitmask(2), usize::MAX - 3);
    }

    #[test]
    #[should_panic(expected = "required (non-optional) subscribers")]
    fn test_more_than_bitwidth_gating_subscribers_panics() {
        compute_bitmask(65);
    }

    #[test]
    fn test_optional_subscriber_drain_does_not_block_retriggering() {
        let enqueue_count = Arc::new(AtomicUsize::new(0));
        let enqueuer =
            Arc::new(CountingEnqueuer(enqueue_count.clone())) as Arc<dyn CallbackNodeEnqueuer>;

        let callback = VecPorts {
            subs: vec![
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: false,
                    capacity: 1,
                    is_trigger: true,
                    keep_across_runs: true,
                    channel_name: "required".into(),
                })),
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: true,
                    capacity: 1,
                    is_trigger: false,
                    keep_across_runs: true,
                    channel_name: "optional".into(),
                })),
            ],
            pubs: vec![],
        };

        let mut node = CallbackNode::new_named(Box::new(callback), "mixed".into());
        node.register_with_executor(0, enqueuer);

        let collected = node.callback().collect_subscribers();
        let (Some(SubscriberReadiness::Gating(readiness, bit_index)), None) = (
            collected[0].readiness_state(),
            collected[1].readiness_state(),
        ) else {
            panic!("unexpected readiness states");
        };

        readiness.set_bit(bit_index);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            1,
            "first data arrival should enqueue the node"
        );
        node.drain_subscribers();
        readiness.set_bit(bit_index);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            2,
            "node must re-trigger after optional subscriber drains"
        );
    }

    #[test]
    fn test_required_non_trigger_input_gates_until_it_has_a_value() {
        use crate::output::Output;
        use crate::publisher::{Publisher, PublisherConfig};
        use crate::time::FrameworkTime;

        let enqueue_count = Arc::new(AtomicUsize::new(0));
        let enqueuer =
            Arc::new(CountingEnqueuer(enqueue_count.clone())) as Arc<dyn CallbackNodeEnqueuer>;

        let mut trigger_pub = Publisher::<u64>::new(PublisherConfig {
            capacity: 1,
            channel_name: "trigger".into(),
        });
        let mut gate_pub = Publisher::<u64>::new(PublisherConfig {
            capacity: 1,
            channel_name: "gate".into(),
        });

        let callback = VecPorts {
            subs: vec![
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: false,
                    capacity: 1,
                    is_trigger: true,
                    keep_across_runs: true,
                    channel_name: "trigger".into(),
                })),
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: false,
                    capacity: 1,
                    is_trigger: false,
                    keep_across_runs: true,
                    channel_name: "gate".into(),
                })),
            ],
            pubs: vec![],
        };

        let mut node = CallbackNode::new_named(Box::new(callback), "gated".into());
        node.register_with_executor(0, enqueuer);

        {
            let (mut subs, _) = node.callback_mut().collect_ports_mut();
            trigger_pub.connect_to_subscriber(&mut *subs[0]).unwrap();
            gate_pub.connect_to_subscriber(&mut *subs[1]).unwrap();
        }
        trigger_pub.allocate_arena();
        gate_pub.allocate_arena();

        let time = FrameworkTime::from_nanoseconds(1);

        {
            let mut out = Output::new_default(&mut trigger_pub);
            *out = 1;
            out.send();
        }
        trigger_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            0,
            "trigger alone must not run the node"
        );

        {
            let mut out = Output::new_default(&mut gate_pub);
            *out = 10;
            out.send();
        }
        gate_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            1,
            "gate value arriving after the trigger must run the node"
        );

        node.drain_subscribers();

        {
            let mut out = Output::new_default(&mut trigger_pub);
            *out = 2;
            out.send();
        }
        trigger_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            2,
            "new trigger data must re-run the node while the gate retains its value"
        );

        node.drain_subscribers();

        {
            let mut out = Output::new_default(&mut gate_pub);
            *out = 11;
            out.send();
        }
        gate_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            2,
            "gate data alone must not trigger the node"
        );
    }

    #[test]
    fn test_optional_trigger_input_fires_node() {
        use crate::output::Output;
        use crate::publisher::{Publisher, PublisherConfig};
        use crate::time::FrameworkTime;

        let enqueue_count = Arc::new(AtomicUsize::new(0));
        let enqueuer =
            Arc::new(CountingEnqueuer(enqueue_count.clone())) as Arc<dyn CallbackNodeEnqueuer>;

        let mut publisher = Publisher::<u64>::new(PublisherConfig {
            capacity: 2,
            channel_name: "opt_trig".into(),
        });

        let callback = VecPorts {
            subs: vec![Box::new(Subscriber::<u64>::new(SubscriberConfig {
                is_optional: true,
                capacity: 2,
                is_trigger: true,
                keep_across_runs: true,
                channel_name: "opt_trig".into(),
            }))],
            pubs: vec![],
        };

        let mut node = CallbackNode::new_named(Box::new(callback), "optional_triggered".into());
        node.register_with_executor(0, enqueuer);
        enqueue_count.store(0, Ordering::Relaxed);

        {
            let (mut subs, _) = node.callback_mut().collect_ports_mut();
            publisher.connect_to_subscriber(&mut *subs[0]).unwrap();
        }
        publisher.allocate_arena();

        let time = FrameworkTime::from_nanoseconds(1);
        for i in 0..3u64 {
            {
                let mut out = Output::new_default(&mut publisher);
                *out = i;
                out.send();
            }
            publisher.flush_loaned_values(time);
            assert_eq!(
                enqueue_count.load(Ordering::Relaxed) as u64,
                i + 1,
                "every optional-trigger arrival must enqueue the node"
            );
            node.drain_subscribers();
        }
    }

    #[test]
    fn test_optional_trigger_respects_required_gate() {
        use crate::output::Output;
        use crate::publisher::{Publisher, PublisherConfig};
        use crate::time::FrameworkTime;

        let enqueue_count = Arc::new(AtomicUsize::new(0));
        let enqueuer =
            Arc::new(CountingEnqueuer(enqueue_count.clone())) as Arc<dyn CallbackNodeEnqueuer>;

        let mut gate_pub = Publisher::<u64>::new(PublisherConfig {
            capacity: 1,
            channel_name: "gate".into(),
        });
        let mut opt_pub = Publisher::<u64>::new(PublisherConfig {
            capacity: 1,
            channel_name: "opt_trig".into(),
        });

        let callback = VecPorts {
            subs: vec![
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: false,
                    capacity: 1,
                    is_trigger: false,
                    keep_across_runs: true,
                    channel_name: "gate".into(),
                })),
                Box::new(Subscriber::<u64>::new(SubscriberConfig {
                    is_optional: true,
                    capacity: 1,
                    is_trigger: true,
                    keep_across_runs: true,
                    channel_name: "opt_trig".into(),
                })),
            ],
            pubs: vec![],
        };

        let mut node = CallbackNode::new_named(Box::new(callback), "gated_optional_trigger".into());
        node.register_with_executor(0, enqueuer);

        {
            let (mut subs, _) = node.callback_mut().collect_ports_mut();
            gate_pub.connect_to_subscriber(&mut *subs[0]).unwrap();
            opt_pub.connect_to_subscriber(&mut *subs[1]).unwrap();
        }
        gate_pub.allocate_arena();
        opt_pub.allocate_arena();

        let time = FrameworkTime::from_nanoseconds(1);

        {
            let mut out = Output::new_default(&mut opt_pub);
            *out = 1;
            out.send();
        }
        opt_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            0,
            "optional trigger must not fire while a required input is empty"
        );

        {
            let mut out = Output::new_default(&mut gate_pub);
            *out = 10;
            out.send();
        }
        gate_pub.flush_loaned_values(time);
        assert_eq!(enqueue_count.load(Ordering::Relaxed), 1);

        node.drain_subscribers();

        {
            let mut out = Output::new_default(&mut opt_pub);
            *out = 2;
            out.send();
        }
        opt_pub.flush_loaned_values(time);
        assert_eq!(
            enqueue_count.load(Ordering::Relaxed),
            2,
            "optional trigger must fire once the gate retains a value"
        );
    }

    #[test]
    fn test_forwarded_channel_usage_accounts_for_write_and_read_buffers() {
        use crate::forwarded_message::ForwardedMessage;
        use crate::publisher::{ForwardingPublisher, PublisherConfig};

        const FORWARDED: &str = "forwarded";

        struct Forwarder {
            publisher: ForwardingPublisher<bool, u64>,
        }
        impl Callback for Forwarder {
            fn run(&mut self, _ctx: &crate::context::Context) -> Run {
                Run::new(0)
            }
            fn for_each_subscriber<'a>(&'a self, _f: &mut dyn FnMut(&'a dyn GenericSubscriber)) {}
            fn for_each_publisher<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericPublisher)) {
                f(&self.publisher);
            }
            fn for_each_subscriber_mut<'a>(
                &'a mut self,
                _f: &mut dyn FnMut(&'a mut dyn GenericSubscriber),
            ) {
            }
            fn for_each_publisher_mut<'a>(
                &'a mut self,
                f: &mut dyn FnMut(&'a mut dyn GenericPublisher),
            ) {
                f(&mut self.publisher);
            }
            fn for_each_port_mut<'a>(&'a mut self, f: &mut dyn FnMut(PortMut<'a>)) {
                f(PortMut::Publisher(&mut self.publisher));
            }
        }

        struct Receiver {
            subscriber: Subscriber<ForwardedMessage<bool, u64>>,
        }
        impl Callback for Receiver {
            fn run(&mut self, _ctx: &crate::context::Context) -> Run {
                Run::new(0)
            }
            fn for_each_subscriber<'a>(&'a self, f: &mut dyn FnMut(&'a dyn GenericSubscriber)) {
                f(&self.subscriber);
            }
            fn for_each_publisher<'a>(&'a self, _f: &mut dyn FnMut(&'a dyn GenericPublisher)) {}
            fn for_each_subscriber_mut<'a>(
                &'a mut self,
                f: &mut dyn FnMut(&'a mut dyn GenericSubscriber),
            ) {
                f(&mut self.subscriber);
            }
            fn for_each_publisher_mut<'a>(
                &'a mut self,
                _f: &mut dyn FnMut(&'a mut dyn GenericPublisher),
            ) {
            }
            fn for_each_port_mut<'a>(&'a mut self, f: &mut dyn FnMut(PortMut<'a>)) {
                f(PortMut::Subscriber(&mut self.subscriber));
            }
        }

        let nodes = vec![
            CallbackNode::new_named(
                Box::new(Forwarder {
                    publisher: ForwardingPublisher::<bool, u64>::new(
                        PublisherConfig {
                            capacity: 1,
                            channel_name: FORWARDED.into(),
                        },
                        vec![FORWARDED.into()],
                    ),
                }),
                "Forwarder".into(),
            ),
            CallbackNode::new_named(
                Box::new(Receiver {
                    subscriber: Subscriber::<ForwardedMessage<bool, u64>>::new(SubscriberConfig {
                        is_optional: true,
                        capacity: 4,
                        is_trigger: true,
                        keep_across_runs: true,
                        channel_name: FORWARDED.into(),
                    }),
                }),
                "Receiver4".into(),
            ),
            CallbackNode::new_named(
                Box::new(Receiver {
                    subscriber: Subscriber::<ForwardedMessage<bool, u64>>::new(SubscriberConfig {
                        is_optional: true,
                        capacity: 3,
                        is_trigger: true,
                        keep_across_runs: true,
                        channel_name: FORWARDED.into(),
                    }),
                }),
                "Receiver3".into(),
            ),
        ];

        let usage = super::find_forwarded_channel_usage(&nodes);
        assert_eq!(
            usage.get(&String::from(FORWARDED)).copied(),
            Some(2 * 4 + 2 * 3),
            "each subscriber contributes 2 * capacity (write + read buffers)"
        );
    }
}
