load("//bazel:rust.bzl", "miri_test", "rust_library", "rust_test")
load("@crates//:defs.bzl", "all_crate_deps")

package(default_visibility = ["//visibility:public"])

rust_library(
    name = "simulation_executor",
    srcs = glob(["src/**/*.rs"]),
    crate_features = ["log_simulation"],
    deps = all_crate_deps(normal = True),
)

rust_test(
    name = "simulation_executor_unit_tests",
    crate = ":simulation_executor",
    crate_features = ["log_simulation"],
    deps = all_crate_deps(normal_dev = True),
)

miri_test(
    name = "simulation_executor_miri",
    srcs = glob(["src/**/*.rs"]),
    rustc_flags = [
        "--cfg",
        'feature="log_simulation"',
    ],
    deps = all_crate_deps(
        normal = True,
        normal_dev = True,
    ),
)
